version: "3"

services:
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: gabbles
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5432:5432"
